### ISSUE TITLE
Lead function not found

### ISSUE THREAD

**Issue by satssin** [arusso/puppet-iptables#22]
we downloaded arusso-iptables module to manage our ip table rules, in one of our module we are calling below arusso-iptables class, When we are applying this on agent its giving below error.

fo: Loading facts in /var/opt/lib/pe-puppet/lib/facter/f0003.rb
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Unknown function lead at /etc/puppetlabs/puppet/environments/common/iptables/manifests/ipv4.pp:29 on node us-east-1b.engradepro.sftpcluster.pqa.50-253.mhecloud.aws
 
iptables::rule { 'Client sftp access':
comment => 'This allow access to our sftp servers from clients machines',
order => '10',
destination_port => $admin_ports,
protocol => 'tcp',
action => 'ACCEPT',
source => $whitelist,
}
#Reject all others#
iptables::rule { 'Reject all other connections':
comment => 'Reject SSH from all other workstations',
order => '150',
destination_port => $admin_ports,
protocol => 'tcp',
action => 'REJECT',
}

**Comment by arusso** [comment]
Did you install with puppet module install? If so it should have pulled down the dependency of arusso-oski module, which has that function.

**Comment by satssin** [comment]
I added it in my puppetfile [R10k] to pull the module down from forge. do i need to mentioned anything else.



forge 'forge.puppetlabs.com'

# Forge modules

mod 'arusso/iptables', '1.2.1'



Satish


973-289-6721


________________________________

**Comment by arusso** [comment]
It looks like dependencies are not automatically downloaded, at least based on my reading of puppetlabs/r10k#38.

You will want to add a line like:

     mod 'arusso/oski'

**Comment by satssin** [comment]
Thanks alot Aaron,  i will include it.



Satish


973-289-6721


________________________________
